ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-c"]

RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && apt-get install -y \
    ros-humble-isaac-ros-examples \
    ros-humble-isaac-ros-visual-slam \
    && rm -rf /var/lib/apt/lists/*
