FROM arm64v8/ros:humble-ros-base

SHELL ["/bin/bash", "-lc"]

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-empy \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# Nice default shell behavior for interactive dev
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc
